---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.downloads

    config:
        locations:
            - file:/data/downloads/config/downloads-config.properties
            - file:/data/downloads/config/downloads-config.yml
            - file:/data/downloads/config/downloads-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    http:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
server:
    session:
        timeout: 7200 # seconds, 2 hours
    tomcat:
        port-header: 'X-Forwarded-Port'
        protocol-header: 'X-Forwarded-Proto'
        remote-ip-header: 'X-Forwarded-For'

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
skin:
    layout: "main"
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
privacyPolicy: "http://www.ala.org.au/about/terms-of-use/privacy-policy/"

security:
    cas:
        casServerName : 'https://auth.ala.org.au'
        uriFilterPattern : '/download/.*,/recordCount/.*,/admin/.*,/admin'
        uriExclusionFilterPattern: '/images.*,/css.*,/js.*,/less.*'
        authenticateOnlyIfLoggedInPattern : '/p,/project,/p/.*,/project/.*,/,/.*'
        loginUrl : 'https://auth.ala.org.au/cas/login'
        logoutUrl : 'https://auth.ala.org.au/cas/logout'
        casServerUrlPrefix : 'https://auth.ala.org.au/cas'
        bypass : false

environments:
    development:
        grails:
            serverURL: "http://devt.ala.org.au:8080/ala-downloads"
            mail:
                host: "localhost"
                port: 1025
                username: postie.emailSender
        security:
            cas:
                appServerName: "http://devt.ala.org.au:8080"
    test:
        security:
            cas:
                appServerName: "http://auth.ala.org.au"
    production:
        grails:
            serverURL: "http://auth.ala.org.au/ala-downloads"
            mail:
                host: "localhost"
                port: 25
        security:
            cas:
                appServerName: "http://auth.ala.org.au"

---
hibernate:
    show_sql: false
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost/downloads
            logSql: alse
            username: "postgres"
            password: "password"

    test:
        dataSource:
            dbCreate: update

    production:
        dataSource:
            dbCreate: update
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
